platform :ios, '8.0'

workspace 'WechatShortVideoDemo'

xcodeproj 'WechatShortVideoDemo.xcodeproj'

target 'WechatShortVideoDemo' do
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'SCRecorder', '~> 2.6.1'
    pod 'PureLayout', '~> 3.0.1'
    xcodeproj 'WechatShortVideoDemo.xcodeproj'
end


